#!/bin/bash

rm ~/x

termux-setup-storage & sleep 4

while true; do
    if [ -e ~/storage ]; then
        break
    else
        echo "Storage permission denied"
    fi
    sleep 3
done

echo "Installing termux packages"
apt-get clean
apt-get update
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade
pkg install x11-repo -y
pkg install pulseaudio -y
pkg install xwayland -y
pkg install wget -y
pkg install tsu -y
pkg install root-repo -y
pkg install patchelf -y
pkg install p7zip -y
pkg install xorg-xrandr -y
pkg install ncurses-utils -y
pkg install hashdeep -y
pkg install termux-x11-nightly -y

if [ -e $PREFIX/glibc ]; then
    echo -n "Removing previous glibc. Continue? (Y/n) "
    read i
    if [ "$i" = "Y" ] || [ "$i" = "y" ]; then
        rm -rf $PREFIX/glibc
    else
        return 1
    fi
fi

echo "Installing mobox"

echo "Updating package manager"
mkdir -p $PREFIX/glibc/opt/package-manager/installed
echo "PRIVATE_TOKEN=glpat-Xs4HfrCkMpbedkPycqzP
PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token
. $PREFIX/glibc/opt/package-manager/token
function wget-git-q {
    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
    return $?
}
wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"
. $PREFIX/glibc/opt/package-manager/package-manager
sync-all
sync-package wine-ge-custom
ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/mobox

echo "To start - type \"mobox\""
